// Voice acting playback. Clips live in assets/voice/<id>.mp3 where id is a hash
// of speaker+text — generated by tools/generate_voices.py (ElevenLabs, runs on
// Hiro's machine with his key). Missing clip = silence. Music ducks while a line plays.

const VoiceMan = {
  current: null, _missing: {},

  // fnv1a-32 — must match tools/build_voice_manifest.js exactly
  hash(s) {
    let h = 0x811c9dc5;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = (h * 0x01000193) >>> 0; }
    return ('0000000' + h.toString(16)).slice(-8);
  },

  // dialog-title -> voice speaker normalization (must match the manifest builder)
  speakerFor(rawName) {
    const n = rawName.split('·')[0].trim().toUpperCase();
    const MAP = {
      'SIGNPOST': 'NARRATOR', 'THE WELL': 'NARRATOR', 'THE WAYSTATION': 'NARRATOR',
      'THE NIGHT SHIPMENT': 'NARRATOR', 'THE CRATES OPEN': 'NARRATOR', 'AN EMPTY ROAD': 'NARRATOR',
      'LEY-LINE NODE': 'NARRATOR', 'THE DRAGON EMPEROR': 'ANKUNYX',
      'A STRANGER IN THE TREELINE': 'SHEN SAMA',
      // the Seraphim's road
      'THE TREATY STONE': 'NARRATOR', 'THE SPINE TRAIL': 'NARRATOR', 'THE SKYREACH SHRINE': 'NARRATOR',
      'KARGOTH, WHO CARRIES THE HILL': 'KARGOTH', 'SKARVA RED-BLADE': 'SKARVA',
      'KING NIBNOB THE THRICE-CROWNED': 'NIBNOB', 'VESSHK OF THE HIGH WIND': 'NARRATOR', // she speaks like weather: the narrator carries her
      'AURVAETH THE TREATY-BOUND': 'AURVAETH',
      // the warlock's epilogue
      'THE PLAZA, AFTER': 'NARRATOR', 'A LETTER WITH NO SEAL': 'NARRATOR', 'THE BLACK CARRIAGE': 'NARRATOR',
      'THE WORKING DEAD': 'NARRATOR', 'THE BOUNDARY STONE': 'NARRATOR', 'THE ASHENVEIL ACADEMY': 'NARRATOR',
      'SER HALDRIC': 'HALDRIC', 'INQUISITOR SALLOW': 'SALLOW',
      'THE PALE COURIER': 'PALE COURIER', 'LADY NYX': 'NYX',
    };
    return MAP[n] || n;
  },

  // player character speaks their chosen line; the NPC reply queues behind it
  sayPlayer(label) {
    if (!window.GameState || !GameState.player || !label) return;
    this.say('PLAYER-' + GameState.player.char.toUpperCase(), label, true);
  },

  say(rawName, text, isPlayer) {
    if (!text) return;
    const speaker = this.speakerFor(rawName);
    const id = this.hash(speaker + '|' + text);
    if (this._missing[id]) { if (isPlayer) return; }
    if (!isPlayer && this.current && this._playerActive && !this.current.ended) {
      this._pending = [rawName, text];           // let the player's line finish first
      return;
    }
    if (this._missing[id]) return;
    this.stop(); this._pending = null;
    const a = new Audio('assets/voice/' + id + '.mp3');
    a.volume = 0.95;
    this._playerActive = !!isPlayer;
    a.addEventListener('error', () => { this._missing[id] = true;
      this._playerActive = false;
      if (this.current === a) this.current = null; // failed clip = nothing is speaking
      if (this._pending) { const p = this._pending; this._pending = null; this.say(p[0], p[1]); } });
    const music = window.MusicMan && MusicMan.current;
    if (music) music.volume = Math.min(music.volume, 0.18); // duck
    a.addEventListener('ended', () => {
      this._playerActive = false;
      if (this._pending) { const p = this._pending; this._pending = null; this.say(p[0], p[1]); return; }
      if (music && MusicMan.current === music) music.volume = MusicMan.vol;
    });
    const p = a.play(); if (p && p.catch) p.catch(() => { if (music) music.volume = MusicMan.vol; });
    this.current = a;
  },

  stop() {
    if (this.current) { try { this.current.pause(); } catch (e) {}
      if (window.MusicMan && MusicMan.current) MusicMan.current.volume = MusicMan.vol;
      this.current = null; }
  },
};
if (typeof window !== 'undefined') window.VoiceMan = VoiceMan;
if (typeof module !== 'undefined' && module.exports) module.exports = { VoiceMan };
