// Voice acting playback. Clips live in assets/voice/<id>.mp3 where id is a hash
// of speaker+text — generated by tools/generate_voices.py (ElevenLabs, runs on
// Hiro's machine with his key). Missing clip = silence. Music ducks while a line
// plays and ALWAYS un-ducks afterward (even on a missing/errored clip), so the
// game's audio can never get stuck quiet. State can never wedge: every play path
// clears _playerActive/_pending and restores music.

const VoiceMan = {
  current: null, _missing: {}, _pending: null, _playerActive: false,
  vol: 0.95, _duckedTrack: null,

  // fnv1a-32 — must match tools/build_voice_manifest.js exactly
  hash(s) {
    let h = 0x811c9dc5;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = (h * 0x01000193) >>> 0; }
    return ('0000000' + h.toString(16)).slice(-8);
  },

  // dialog-title -> voice speaker normalization (must match the manifest builder)
  speakerFor(rawName) {
    const n = rawName.split('·')[0].trim().toUpperCase();
    const MAP = {
      'SIGNPOST': 'NARRATOR', 'THE WELL': 'NARRATOR', 'THE WAYSTATION': 'NARRATOR',
      'THE NIGHT SHIPMENT': 'NARRATOR', 'THE CRATES OPEN': 'NARRATOR', 'AN EMPTY ROAD': 'NARRATOR',
      'LEY-LINE NODE': 'NARRATOR', 'THE DRAGON EMPEROR': 'ANKUNYX',
      'A STRANGER IN THE TREELINE': 'SHEN SAMA',
      // the Seraphim's road
      'THE TREATY STONE': 'NARRATOR', 'THE SPINE TRAIL': 'NARRATOR', 'THE SKYREACH SHRINE': 'NARRATOR',
      'KARGOTH, WHO CARRIES THE HILL': 'KARGOTH', 'SKARVA RED-BLADE': 'SKARVA',
      'KING NIBNOB THE THRICE-CROWNED': 'NIBNOB', 'VESSHK OF THE HIGH WIND': 'NARRATOR', // she speaks like weather: the narrator carries her
      'AURVAETH THE TREATY-BOUND': 'AURVAETH',
      // the warlock's epilogue
      'THE PLAZA, AFTER': 'NARRATOR', 'A LETTER WITH NO SEAL': 'NARRATOR', 'THE BLACK CARRIAGE': 'NARRATOR',
      'THE WORKING DEAD': 'NARRATOR', 'THE BOUNDARY STONE': 'NARRATOR', 'THE ASHENVEIL ACADEMY': 'NARRATOR',
      'SER HALDRIC': 'HALDRIC', 'INQUISITOR SALLOW': 'SALLOW',
      'THE PALE COURIER': 'PALE COURIER', 'LADY NYX': 'NYX',
      // proving-grounds hunt flavor (non-warlock arrivals)
      'THE PROVING GROUNDS': 'NARRATOR',
    };
    return MAP[n] || n;
  },

  DUCK: 0.10, // music sits well under a voice line (voice plays at this.vol ~0.95)

  // is a clip (or a queued reply) actively speaking right now?
  isSpeaking() {
    return !!(this._pending || (this.current && !this.current.ended && !this.current.paused));
  },

  // ---- music duck/restore — follows the CURRENT track, even across zone changes ----
  // MusicMan honors the _duckedByVoice flag in its fade so a track that starts
  // mid-line comes up ducked instead of drowning the voice.
  _duck() {
    if (!window.MusicMan) return;
    MusicMan._duckedByVoice = true;
    if (MusicMan.current) MusicMan.current.volume = Math.min(MusicMan.current.volume, this.DUCK);
  },
  _unduck() {
    if (!window.MusicMan) return;
    MusicMan._duckedByVoice = false;
    if (MusicMan.current && !MusicMan.muted) MusicMan.current.volume = MusicMan.vol;
  },

  // player character speaks their chosen line; the NPC reply queues behind it
  sayPlayer(label) {
    if (!window.GameState || !GameState.player || !label) return;
    this.say('PLAYER-' + GameState.player.char.toUpperCase(), label, true);
  },

  say(rawName, text, isPlayer) {
    if (!text) return;
    const speaker = this.speakerFor(rawName);
    const id = this.hash(speaker + '|' + text);

    // an NPC reply waits behind the player's line — but only if the player's line
    // is genuinely still playing. (A missing player clip never blocks the reply.)
    if (!isPlayer && this._playerActive && this.current && !this.current.ended && !this.current.paused) {
      this._pending = [rawName, text];
      return;
    }
    // a clip we already know is absent: skip it, but still un-duck and flush the queue
    if (this._missing[id]) {
      this._afterClip(isPlayer);
      return;
    }

    this.stop(); this._pending = null;
    const a = new Audio('assets/voice/' + id + '.mp3');
    a.volume = this.vol;
    this._playerActive = !!isPlayer;
    this.current = a;
    this._duck();
    const finish = (failed) => {
      if (failed) this._missing[id] = true;
      if (this.current === a) this.current = null;
      this._afterClip(isPlayer);
    };
    a.addEventListener('error', () => finish(true));
    a.addEventListener('ended', () => finish(false));
    const p = a.play();
    if (p && p.catch) p.catch(() => {}); // autoplay-blocked: 'ended' won't fire, watchdog covers it
  },

  // common tail for every clip outcome: drop player-flag, un-duck, play any queued reply
  _afterClip(wasPlayer) {
    this._playerActive = false;
    if (this._pending) { const pnd = this._pending; this._pending = null; this.say(pnd[0], pnd[1]); return; }
    this._unduck();
  },

  stop() {
    if (this.current) { try { this.current.pause(); } catch (e) {} this.current = null; }
    this._playerActive = false;
    this._unduck();
  },
};
if (typeof window !== 'undefined') window.VoiceMan = VoiceMan;
if (typeof module !== 'undefined' && module.exports) module.exports = { VoiceMan };
